require("mason").setup()
require("mason-lspconfig").setup({
    ensure_installed = {
        "lua_ls",
        "bashls",
        "clangd",
        "cmake",
        "dockerls",
        "docker_compose_language_service",
        "html",
        "jsonls",
        "ltex",
        "markdown_oxide",
        "intelephense",
        "pyright",
        "sqlls",
        "yamlls"
    },
    handlers = {
        function(lua_ls)
            require('lspconfig')[lua_ls].setup({})
        end,
        function(clangd)
            require('lspconfig')[clangd].setup({})
        end,
        function(jsonls)
            require('lspconfig')[jsonls].setup({})
        end,
        function(intelephense)
            require('lspconfig')[intelephense].setup({})
        end,
        function(pyright)
            require('lspconfig')[pyright].setup({})
        end,
        function(sqlls)
            require('lspconfigc')[sqlls].setup({})
        end,
    }
})
